services:
  shiranui:
    image: ghcr.io/ignismirage/shiranui:latest
    pull_policy: always
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
